### ISSUE TITLE
Is it possible to support deployment target 8.0.

### ISSUE THREAD

**Issue by ansu** [recruit-lifestyle/Smile-Lock#12]
HI Smile Team,

Thanks for building super library. We want to use this library but we have to give minimum deployment support 8.0. Could you please guide us.

**Comment by liu044100** [comment]
Hi @ansu,  sorry about it, but this pod supports iOS9.0+, because this pods use `UIStackView`  and `NSLayoutAnchor` that only upports iOS9.0+.

If you want to support iOS8, you have to rewrite the code that use `NSLayoutAnchor` and recreate storyboard that is made by `UIStackView`.
