### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by scottrhoyt** [recruit-lifestyle/Smile-Lock#16]
Would love to use your library. Please consider adding [Carthage support](https://github.com/Carthage/Carthage#supporting-carthage-for-your-framework).

**Comment by liu044100** [comment]
Hi, @scottrhoyt 

Thanks for your advice. I will check it.

**Comment by scottrhoyt** [comment]
Thank you for considering!

**Comment by liu044100** [comment]
Hi, @scottrhoyt 

Sorry for implement it late.

Actually, I am a Carthage beginner... I don't know whether my practice is the correct approach.

I made [a new branch](https://github.com/recruit-lifestyle/Smile-Lock/tree/Carthage) to support Carthage.

You can add `github "recruit-lifestyle/Smile-Lock"` to your Cartfile, and check whether it works.
