### ISSUE TITLE
Unable to simultaneously satisfy constraints.

### ISSUE THREAD

**Issue by amayatsky** [recruit-lifestyle/Smile-Lock#17]
Good day!

`<viewController storyboardIdentifier="PinEntryViewController" title="Disable Alarm" id="ZR3-X1-TCn" customClass="PinEntryViewController" customModule="Occly" customModuleProvider="target" sceneMemberID="viewController">
                    <layoutGuides>
                        <viewControllerLayoutGuide type="top" id="LVW-UC-Lj0"/>
                        <viewControllerLayoutGuide type="bottom" id="Ond-1g-An4"/>
                    </layoutGuides>
                    <view key="view" contentMode="scaleToFill" id="knG-LB-ggv">
                        <rect key="frame" x="0.0" y="0.0" width="375" height="667"/>
                        <autoresizingMask key="autoresizingMask" widthSizable="YES" heightSizable="YES"/>
                        <subviews>
                            <stackView opaque="NO" contentMode="scaleToFill" axis="vertical" translatesAutoresizingMaskIntoConstraints="NO" id="2h7-T2-haX">
                                <rect key="frame" x="0.0" y="0.0" width="375" height="667"/>
                            </stackView>
                        </subviews>
                        <color key="backgroundColor" white="1" alpha="1" colorSpace="calibratedWhite"/>
                        <constraints>
                            <constraint firstItem="2h7-T2-haX" firstAttribute="centerY" secondItem="knG-LB-ggv" secondAttribute="centerY" id="0tz-9F-sJ7"/>
                            <constraint firstItem="2h7-T2-haX" firstAttribute="height" secondItem="knG-LB-ggv" secondAttribute="height" id="1r7-ak-Qcg"/>
                            <constraint firstItem="2h7-T2-haX" firstAttribute="centerX" secondItem="knG-LB-ggv" secondAttribute="centerX" id="s1Q-mw-UYj"/>
                            <constraint firstItem="2h7-T2-haX" firstAttribute="width" secondItem="knG-LB-ggv" secondAttribute="width" id="xgF-5W-UUU"/>
                        </constraints>
                    </view>
                    <connections>
                        <outlet property="pinContainerView" destination="2h7-T2-haX" id="EeG-bq-pZe"/>
                    </connections>
                </viewController>`
I have this view controller and when calling `passwordContainerView = PasswordContainerView.create(in: pinContainerView, digit: 4)`
I get the following error:
[LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x6080002950e0 UIStackView:0x7f8464d5b1a0.height == UIView:0x7f8464d5b610.height   (active)>",
    "<NSLayoutConstraint:0x608000295180 UIStackView:0x7f8464d5b1a0.width == UIView:0x7f8464d5b610.width   (active)>",
    "<NSLayoutConstraint:0x60000028fd70 SmileLock.PasswordContainerView:0x7f8464d5dba0.width == 0.702439*SmileLock.PasswordContainerView:0x7f8464d5dba0.height   (active)>",
    "<NSLayoutConstraint:0x600000292660 'UISV-canvas-connection' UIStackView:0x7f8464d5b1a0.top == SmileLock.PasswordContainerView:0x7f8464d5dba0.top   (active)>",
    "<NSLayoutConstraint:0x600000292610 'UISV-canvas-connection' V:[SmileLock.PasswordContainerView:0x7f8464d5dba0]-(0)-|   (active, names: '|':UIStackView:0x7f8464d5b1a0 )>",
    "<NSLayoutConstraint:0x600000292700 'UISV-canvas-connection' UIStackView:0x7f8464d5b1a0.leading == SmileLock.PasswordContainerView:0x7f8464d5dba0.leading   (active)>",
    "<NSLayoutConstraint:0x60000028e100 'UISV-canvas-connection' H:[SmileLock.PasswordContainerView:0x7f8464d5dba0]-(0)-|   (active, names: '|':UIStackView:0x7f8464d5b1a0 )>",
    "<NSLayoutConstraint:0x608000295db0 'UIView-Encapsulated-Layout-Height' UIView:0x7f8464d5b610.height == 460   (active)>",
    "<NSLayoutConstraint:0x608000294dc0 'UIView-Encapsulated-Layout-Width' UIView:0x7f8464d5b610.width == 320   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x60000028fd70 SmileLock.PasswordContainerView:0x7f8464d5dba0.width == 0.702439*SmileLock.PasswordContainerView:0x7f8464d5dba0.height   (active)>

How to fix that? :)

Thank you in advance!

**Comment by amayatsky** [comment]
I have lowered the priority of my constraints and the warning disappeared.

**Comment by liu044100** [comment]
Hi, @amayatsky 

Sorry for late reply.

It seems the `PasswordContainerView`'s inner constraints conflict with the `UIView:0x7f8464d5b610`'s constraints.

`PasswordContainerView`'s inner constraints as below:

```swift
fileprivate let kDefaultWidth: CGFloat = 288
    fileprivate let kDefaultHeight: CGFloat = 410
    fileprivate var widthConstraint: NSLayoutConstraint!
    
    fileprivate func configureConstraints() {
        let ratioConstraint = widthAnchor.constraint(equalTo: self.heightAnchor, multiplier: kDefaultWidth / kDefaultHeight)
        self.widthConstraint = widthAnchor.constraint(equalToConstant: kDefaultWidth)
        self.widthConstraint.priority = 999
        NSLayoutConstraint.activate([ratioConstraint, widthConstraint])
    }
```


If you want to customize the `PasswordContainerView`'s width & height, the `width/height` have to equal to `kDefaultWidth/kDefaultHeight`.

So my suggestion is that only change the `PasswordContainerViewc's width constraint, and the height will be adjusted automatically following the `ratioConstraint` as above code.
