### ISSUE TITLE
Swift 2.3 (pod version 1.x) is not support iOS 8.0

### ISSUE THREAD

**Issue by gaoshanyu** [recruit-lifestyle/Smile-Lock#18]
Could we have a real version for Swift2.3 to support iOS 8.0?

**Comment by liu044100** [comment]
Hi, @gaoshanyu 

Sorry about that this pod only support iOS9 and later.

**Comment by gaoshanyu** [comment]
Hi @liu044100, I've re-code the library in Swift 2.3 to support iOS8. 
But I'm not familiar with GitHub and I don't know how to pull request here, sorry. 
So I pull it on my GitHub https://github.com/gaoshanyu/SmileLock-iOS8-,  you can take it to your project if you have time and think it is OK. Thanks!

**Comment by liu044100** [comment]
Hi @gaoshanyu , first, thanks for your contribution.

You can check [this tutorial](https://guides.github.com/activities/forking/) about pull request. （[中文版](http://www.tuicool.com/articles/ZnERVn)）
