### ISSUE TITLE
Set license type for GitHub API

### ISSUE THREAD

**Issue by igorkulman** [recruit-lifestyle/Smile-Lock#22]
Your repo has a Apache License but Github and the Github API shows it as "Other". Other repos like Nimble show the license as Apache (https://github.com/Quick/Nimble/blob/master/LICENSE vs https://github.com/recruit-lifestyle/Smile-Lock/blob/master/LICENSE). I think the way to fix this is to edit the license file, set the template for the license as Apache License and then copy your license text back.

I use a script that gets the licenses names for all the libraries my app uses in the Cartfile (https://github.com/pietbrauer/CarthageLicenseScript) and embeds them in the app for legal reasons and this repos shows the license as "Other" instead of "Apache License".

**Comment by liu044100** [comment]
Hello, @igorkulman .

Thanks for advice! I have fixed it.

**Comment by igorkulman** [comment]
Thanks
