### ISSUE TITLE
Can't localize delete button

### ISSUE THREAD

**Issue by fabiocody** [recruit-lifestyle/Smile-Lock#23]
I'm trying to localize the delete button with NSLocalizedString, but the button's label doesn't change when I change the language.

**Comment by liu044100** [comment]
Hello, @fabiocody 

[v2.0.2](https://github.com/recruit-lifestyle/Smile-Lock/releases/tag/2.0.2) add a new property `deleteButtonLocalizedTitle` that can be used for localize.

```swift
passwordContainerView.deleteButtonLocalizedTitle = "smilelock_delete"
```
