### ISSUE TITLE
Adding Cancel or Back Button

### ISSUE THREAD

**Issue by IndraAdam** [recruit-lifestyle/Smile-Lock#24]
Hi, 

How can I add a 'Cancel' button to the Blur Passcode Lock View? The cancel button is just to close the lock view in case the user decided not to enter the passcode.

I hope to be able to put the Cancel button on the left side of number 0.

Thanks for the help in advance.

**Comment by liu044100** [comment]
Hi, @IndraAdam

Sorry for the delayed response.

the left side of number 0 already has [a button for touch id](https://github.com/recruit-lifestyle/Smile-Lock/blob/master/SmileLock-Example/demo_gif/touch_id.png) when the device support it. 

I think you can put the cancel button on left or right bottom corner by using`BlurPasswordLoginViewController` in `PasswordLogin.storyboard`, just like [this](https://www.imore.com/sites/imore.com/files/styles/larger/public/field/image/2016/06/ios-9-review-lock-screen-hero.jpg?itok=8dn89heY).
