### ISSUE TITLE
Pre-set password

### ISSUE THREAD

**Issue by SergeHaddad** [recruit-lifestyle/Smile-Lock#25]
Can we have a pre-set password that the developers sets instead of having the user set it to make the app accessible to few people?

**Comment by liu044100** [comment]
Hi, @SergeHaddad 

You can set a pre-set password , `Smile-Lock` is just a UI component, you have to do it by yourself.

You can refer [this code](https://github.com/recruit-lifestyle/Smile-Lock/blob/master/SmileLock-Example/SmileLock-Example/PasswordLoginViewController.swift#L54-L54) that has a pre-set password "123456".
