### ISSUE TITLE
strange behaviour

### ISSUE THREAD

**Issue by arknee** [recruit-lifestyle/Smile-Lock#26]
Hello, I've been using your smile lock library, I've found some problems:
1- The touchid icon on the lower left appears and dissapears without me doing anything(I mean, when I call the password controller, sometimes is there, and others it isn't, without me changing anything in the code)
If the touchid icon doesn't appear, I can click in the left space, but it won't work, so I think that it really gone.

2- Other problem is when I unlock with the touchid (when it allows me to) it opens again, it only closes definitely when I use the pin number.

3- My last problem it's its performance is being erratic, I mean, I can enter the pin, but the animation on the clicked buttons don't show, or shows later and longer than it should. 
Sometimes it work's amazingly, but others it get really slow. 
Anyway, I think this could be caused by my code, but I tell you for the record.

The two first problems are destroying my head, don't know what it could be.

Thanks :)

**Comment by liu044100** [comment]
Hi, @arknee , could you let me see your code, or give me a demo project that can reappear this problem?

**Comment by arknee** [comment]
Hi, here is my code:

this is my password controller:

```
import UIKit
import SmileLock

class PinController: UIViewController {
    
    @IBOutlet weak var passwordStackView: UIStackView!
    var passwordContainer: PasswordContainerView!

    override func viewDidLoad() {
        super.viewDidLoad()
        passwordContainer = PasswordContainerView.create(in: passwordStackView, digit: 4)
        passwordContainer.delegate = self
        passwordContainer.deleteButtonLocalizedTitle = "⌫"
        passwordContainer.tintColor = UIColor.init(rgb: 0x63A79F)
        passwordContainer.highlightedColor = UIColor.init(rgb: 0x63A79F)
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    

    /*
    // MARK: - Navigation

    // In a storyboard-based application, you will often want to do a little preparation before navigation
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        // Get the new view controller using segue.destinationViewController.
        // Pass the selected object to the new view controller.
    }
    */

}

extension PinController: PasswordInputCompleteProtocol {
    
    func passwordInputComplete(_ passwordContainerView: PasswordContainerView, input: String) {
        if validation(input) {
            self.validationSuccess()
        } else {
            validationFail()
        }
    }
    
    func touchAuthenticationComplete(_ passwordContainerView: PasswordContainerView, success: Bool, error: Error?) {
        if success {
            self.validationSuccess()
        } else {
            passwordContainer.clearInput()
        }
    }
    
}

private extension PinController {

    func validation(_ input: String) -> Bool {
        return input == (UserDefaults.standard.string(forKey: AppConfig.PIN))
    }
    
    func validationSuccess() {
        dismiss(animated: true, completion: nil)
    }
    
    func validationFail() {
        passwordContainer.wrongPassword()
    }   
}
```

and this is how I use it in my main controller:

```
var pinAlreadyShowed = false

//add observer to check when app is in foreground and open pin
override func viewDidLoad() {
	NotificationCenter.default.addObserver(self, selector: #selector(openPin), name: NSNotification.Name.UIApplicationDidBecomeActive, object: nil)
}


//open password controller first time user opens app
override func viewWillAppear(_ animated: Bool) {
        if !pinAlreadyShowed {
            pinAlreadyShowed = true
            openPin()
        }
    }
    
//function to open passwordcontroller
    func openPin() {
        let pinController = (storyboard?.instantiateViewController(withIdentifier: "PinController"))!
        pinController.modalPresentationStyle = .overCurrentContext
        present(pinController, animated: true, completion: nil)
    }
```

Performance is my fault, I have checked :) just have the problem with touchid reopening the password controller and touchid option dissapearing sometimes(can it be cause the phone has the touchid bussy?)

Thanks!

**Comment by liu044100** [comment]
Hi @arknee ,

Sorry about it, I cannot get enough information to know what is wrong, I think `PinController` is no problem.

Could you create a demo project that can reappear this problem?

One suggestion, the sensitive information like password should not be saved in `UserDefaults`, because `UserDefaults` is just XML that can be seen by everyone.

**Comment by arknee** [comment]
Hi, at first thanks for your time. 
I'm going to create a demo and try to reproduce the problem as you told me, and as soon as I got it I'll tell you.
The password in user defaults is just a four digit pin(like the one in onedrive or dropbox apps) for avoid curious people, the real password of the user account is not saved anywhere of course, but thank you for you advice :)

**Comment by arknee** [comment]
Hi again, I've made this example, but I am having problems with "attempt to present view controller on view controller whose view is not in the window hierarchy" and cannot solve it :(
https://github.com/arknee/SmileLockExample
Don't know why is it failing :(
Anyway, I've been doing more tests, and what I've found is that when I unlock with touchid, it appears again, and after some tries, the touchid control dissapears, only allowing me to unlock by pincode.

**Comment by liu044100** [comment]
Hi, @arknee 

I think put `openPin()` in `viewWillAppear` is wrong, put it in `viewDidAppear` will work, don't forget to call `super.viewDidAppear(animated)`

**Comment by liu044100** [comment]
Hi, @arknee

Does it fix your problem?

**Comment by arknee** [comment]
I've done what you told me(view did appear) and it works the same as I had it, but I'll let it this way because it looks more correct(calling the pin once the view is ready).
I just have seen that when I fail logging with touchid several times, it dissapears from the app during some hours (I usually see it again the next day) but I think that has to be with iOS.
Anyway, it's working fine now :)
Thanks for your time!
