### ISSUE TITLE
Smile-Lock issue with iPad Pro

### ISSUE THREAD

**Issue by kkbalaji** [recruit-lifestyle/Smile-Lock#27]
Hello Guys,

We are facing the issue for Smile-Lock in iPad Pro (9.7" with iOS versions 10.3.1) when 3-D touch on while same thing works as expected in iPad Air.

**Screen in iPad Pro(9.7'' with  iOS versions 10.3.1)(having an issue):**
![3](https://user-images.githubusercontent.com/25870168/26968903-6910557a-4d21-11e7-8ad4-fee4bf2a1cdf.PNG)

**Screen in iPad Air(as expected):**
![4](https://user-images.githubusercontent.com/25870168/26968912-7228bddc-4d21-11e7-97c5-dd3f8ed7ff76.PNG)

It will good if someone help us as we are stuck here.

Thanks,
Krushnakant Solanki

**Comment by liu044100** [comment]
Hi, @kkbalaji 

Could you create a demo project that can reappear this problem?

**Comment by liu044100** [comment]
Hi, @kkbalaji

> We are facing the issue for Smile-Lock in iPad Pro (9.7" with iOS versions 10.3.1) when 3-D touch on while same thing works as expected in iPad Air.

Sorry about that I have not a iPad Pro to test, I test [SmileLock-Example](https://github.com/recruit-lifestyle/Smile-Lock/tree/master/SmileLock-Example) in simulator, it works well.

By the way, I think  iPad Pro not support 3D Touch, if you can create a demo project that can reappear this problem, I am glad to help you.
