### ISSUE TITLE
Remove Touch ID Icon From Lock View

### ISSUE THREAD

**Issue by IndraAdam** [recruit-lifestyle/Smile-Lock#28]
Hi,

How can I hide the Touch ID icon & feature from the default Blur Passcode Lock View?

Is there any function that I can call?

Thanks for the help in advance.

**Comment by liu044100** [comment]
You can use this code:

```swift
self.passwordContainerView. touchAuthenticationEnabled = false
```

**Comment by liu044100** [comment]
Hi, @IndraAdam , did this solve your issue?

**Comment by IndraAdam** [comment]
Hi @liu044100, thanks for your quick response.

I am using the BlurPasswordLoginViewController as in one of your example and I cannot find the `passwordContainerView` anywhere in the swift file or storyboard. Is there any other function?

Appreciate your help. Thank you

**Comment by liu044100** [comment]
@IndraAdam 

You can use this:

```swift
passwordUIValidation.view.touchAuthenticationEnabled = false
```
