### ISSUE TITLE
Smile-Lock issue with iPad Pro and Swift3

### ISSUE THREAD

**Issue by kkbalaji** [recruit-lifestyle/Smile-Lock#29]
Hello Guys,

We are facing the issue for Smile-Lock in iPad Pro (9.7" with iOS versions 10.3.1) when 3-D touch on while same thing works as expected in iPad Air. We are facing this issue with Swift3. Please find attached sample code and below screenshot to get more idea.

Screen in iPad Pro(9.7'' with iOS versions 10.3.1)(having an issue):

![smile lock](https://user-images.githubusercontent.com/25870168/28707871-ad967d90-7397-11e7-8d1d-104426433585.jpg)
[SmileLock Demo_Swift3.zip](https://github.com/recruit-lifestyle/Smile-Lock/files/1182363/SmileLock.Demo_Swift3.zip)

It will good if someone help us as we are stuck here.

Thanks,
Krushnakant Solanki

**Comment by liu044100** [comment]
Hello @kkbalaji , I think there is something wrong in your code, `AuthenticateUser()` should be called in `viewDidLoad()`, please put this code to `viewDidAppear()`
