### ISSUE TITLE
errors when installing from cocoapods

### ISSUE THREAD

**Issue by rahulbbit** [recruit-lifestyle/Smile-Lock#33]
I having a few errors while installing from cocoapods

 
![screen shot 2017-09-29 at 5 22 36 pm](https://user-images.githubusercontent.com/11924067/31014916-fa8b7158-a53a-11e7-9145-2d934b068397.png)

**Comment by liu044100** [comment]
Hello, @rahulbbit 

Please check the version, Swift 4 (pod version 3.x), Swift 3 (pod version 2.x), Swift 2.3 (pod version 1.x)

**Comment by rahulbbit** [comment]
![screen shot 2017-09-29 at 7 15 44 pm](https://user-images.githubusercontent.com/11924067/31018709-a383ced6-a54a-11e7-993e-79dd6eff34dc.png)

the pod version is 3.0.0

**Comment by nidhig-sminq** [comment]
I am facing same error, I have install pod version 3.0.0 using swift 4.0. Can you please help how to resolve.

**Comment by liu044100** [comment]
@nidhig-sminq Maybe this can help you.

https://stackoverflow.com/questions/45198857/how-to-build-a-xcode-9-project-with-swift-4-0-using-pods-in-swift-3
