### ISSUE TITLE
3.0.1 does not compile on Swift 4

### ISSUE THREAD

**Issue by rvoortman** [recruit-lifestyle/Smile-Lock#40]
Since the update to 3..0.1, SmileLock refuses to compile on xCode 9 with swift 4. The error is the following: 

`Value of type 'LABiometryType' has no member 'typeFaceID'`

This error can be found in the PasswordContainerView.swift on line 148, in the awakeFromNib() function.

**Comment by liu044100** [comment]
@rvoortman Hello, 3.0.1 works well in my computer, what is the version of your Xcode? 

Maybe clean & build will solve this error.

**Comment by rvoortman** [comment]
@liu044100 Thank you for your superfast reply, I really appreciate it. 
I'm using xCode 9.2 (9C40b). Cleaning and building the project again (also a clean of the existing build directory) does not fix the problem. The conflicting code is as follows:
```
    //MARK: Life Cycle
    open override func awakeFromNib() {
        super.awakeFromNib()
        configureConstraints()
        backgroundColor = .clear
        passwordInputViews.forEach {
            $0.delegate = self
        }
        deleteButton.titleLabel?.adjustsFontSizeToFitWidth = true
        deleteButton.titleLabel?.minimumScaleFactor = 0.5
        touchAuthenticationEnabled = true
        
        var image = touchAuthenticationButton.imageView?.image?.withRenderingMode(.alwaysTemplate)
        
        if #available(iOS 11, *) { 
// THE ERROR IS THROWN IN THE LINE BELOW!
            if touchIDContext.biometryType == .typeFaceID {
                let bundle = Bundle(for: type(of: self))
                image = UIImage(named: "faceid", in: bundle, compatibleWith: nil)?.withRenderingMode(.alwaysTemplate)
            }
        }
        
        touchAuthenticationButton.setImage(image, for: UIControlState())
        touchAuthenticationButton.tintColor = tintColor
    }
```

In the podfile I've added `pod 'SmileLock', '3.0.1'` and `swift4_pods = ['SmileLock']`, together with some other pods.

If you need additional information, feel free to ask.

**Comment by liu044100** [comment]
@rvoortman could you upload a demo project to your github, I will check it

**Comment by liu044100** [comment]
@rvoortman It seems I found what is wrong, I use Xcode 9.1

https://stackoverflow.com/questions/47159343/ios-11-2-local-authentication-type-labiometrytype-has-no-member-typefacei

**Comment by rvoortman** [comment]
@liu044100 If you don't mind, I will not create a demo project, because it seems you've found the problem :)

**Comment by liu044100** [comment]
@rvoortman please check v3.0.2, it fix this issue

**Comment by rvoortman** [comment]
Great, fast response. Thank you so much for the work you've put into this. 
I will update tomorrow :)
