### ISSUE TITLE
How to Create New Pin

### ISSUE THREAD

**Issue by AppleEducate** [recruit-lifestyle/Smile-Lock#42]
How would you take the example you gave to create a new pin code and then validate before going to the home screen?

**Comment by liu044100** [comment]
Hi, @AppleEducate 

It is only a UI component, sorry about that I have not enough time to make a full example...

Maybe you can try [this](https://github.com/liu044100/SmileTouchID). It is a full example from create a new pin to validate it.

**Comment by AppleEducate** [comment]
Thank you! I actually ended up figuring it out. One thing I did that I think would be useful is too add a function to get the input of the view. Just like you can clear the input. That is what I ended up doing to create the pin.
