### ISSUE TITLE
how can i disable and hide touch id and face id

### ISSUE THREAD

**Issue by rexi1rios** [recruit-lifestyle/Smile-Lock#48]
@liu044100 I use below code to configure password view but in the scene, I have face id button and I don't what that. I want to hide this button

` passwordUIValidation = MyPasswordUIValidation(in: passwordStackView)

        passwordUIValidation.success = { [weak self] _ in
            print("*️⃣ success!")
            self?.dismiss(animated: true, completion: nil)
    self?.appDelegate.gotoRepeatView = true
            self?.present("BlurPasswordLoginViewRepeatController")

        }

        passwordUIValidation.failure = {
            //do not forget add [weak self] if the view controller become nil at some point during its lifetime
            print("*️⃣ failure!")
        }

        //visual effect password UI
        passwordUIValidation.view.rearrangeForVisualEffectView(in: self)`

**Comment by liu044100** [comment]
```swift
passwordUIValidation.view.touchAuthenticationButton.isHidden = true
```

**Comment by wixvii** [comment]
When I disable touchID "0" button is leading to left how to fix it ?

**Comment by venkat20390** [comment]
I am facing the issue of @wixvii. The 0 button is leading to left after hiding the touch ID view
