### ISSUE TITLE
Add modifiable font and fontSize

### ISSUE THREAD

**Issue by lucojsmerson** [recruit-lifestyle/Smile-Lock#49]
Hello,

First thank you for this amazing work. For the moment it's impossible to change the font of each passwordInputViews. Could you made if modifiable ?

Thank you very much,

LO.

**Comment by liu044100** [comment]
Hi, @lucojsmerson 

Please check version 3.0.3.

```swift
for view in passwordContainerView.passwordInputViews {
      view.labelFont = // your font
}
```

**Comment by wixvii** [comment]
fontsize is not changing ?
