### ISSUE TITLE
Touch ID Missing

### ISSUE THREAD

**Issue by i-arun-samui** [recruit-lifestyle/Smile-Lock#55]
Hi,

don't you think this is missing in PasswordContainerView.swift ??

 if touchIDContext.biometryType == .touchID {
                let bundle = Bundle(for: type(of: self))
                image = UIImage(named: "Touch", in: bundle, compatibleWith: nil)?.withRenderingMode(.alwaysTemplate)
            }
in simulator the Image is not displayed ??

**Comment by liu044100** [comment]
Hi, @i-arun-samui 

Simulator > Hardware > Touch ID > Enrolled checked, and test it again

**Comment by Ivan411** [comment]
Thank!!! work for me
