### ISSUE TITLE
Issue with TouchID button allowing access after initial touch auth

### ISSUE THREAD

**Issue by moliveira1981** [recruit-lifestyle/Smile-Lock#6]
This happens in the demo app.

After a successful TouchID authentication, subsequent presses of the TouchID button in the pin pad result in auth success without any auth happening

Steps to reproduce:

Start SmileLock demo app on a device w/ TouchID
Tap the TouchId button
Authenticate - auth works as expected
Background the app then bring it back to the foreground
Tap the TouchID button
Results: "Right Password" alert without actually having to authenticate

**Comment by moliveira1981** [comment]
FWIW if anyone else is running into this I get around it by instantiating a new PasswordContainerView each time I present it.

**Comment by liu044100** [comment]
Hi, @moliveira1981.

I also notice this issue yesterday, and push the new code to demo app, the new demo app will dismiss the view controller when Touch ID success.

Thanks for open this issue, you can pull the new code and  check it.

**Comment by liu044100** [comment]
@moliveira1981 If there is no problem, could you close this issue?

**Comment by moliveira1981** [comment]
Looks like the problem is fixed in the example project, thanks!  

Looking a bit closer I believe the underlying problem remains in the component itself.  If it were changed to instantiate a new LAContext() each time the TouchID button is pressed it would avoid allowing the user in automatically and would no longer require component users to recreate the PasswordContainerView to avoid the existing behavior which is subtle, easy to miss, and leaves a pretty huge hole in the security mechanism.   Thoughts?

**Comment by liu044100** [comment]
@moliveira1981  Thanks for your advice. 

In fact, I also have considered this. But I also noticed that when validation success, there is no reason to retain  PasswordContainerView in memory, ViewController should be dismissed, and PasswordContainerView will be released. Because it have already been validated successfully, the password input UI is no longer needed. When the password input UI is shown again,  the LAContext() is a new instance.

Could you tell me a case that need PasswordContainerView to retain in memory when validation success?  If it make sense, I think it should instantiate a new LAContext() each time.

**Comment by moliveira1981** [comment]
We have each independently run into the issue; you with the example project and me where I was keeping a long-lived object in my app that monitored background/foreground transitions and presented the password view.  I changed to now reinstantiate the password view each time it needs to be presented but I don't think there was anything wrong with my previous approach.  

Aside from the two specific examples I would say that if it is possible, somebody will do it.  It would be very easy to implement this in the "wrong" way and never even notice the touch ID button behavior and release your app with a huge security hole.  Of course, you can say they are "not holding it right" (Steve Jobs) but I think it is reasonable for a developer to expect that when you tap the touch id button that you will have to authenticate.  At the very least I believe it would be much safer to default to rejecting subsequent touch id auth attempts as opposed to accepting them - at least that way security would not be compromised.  

Just one man's opinion... thanks for the great component!

**Comment by liu044100** [comment]
Hi @moliveira1981 , thanks for your explanation.

It make sense that "Security would not be compromised." So I pull a new request #7.

Thanks again for your advice.

**Comment by moliveira1981** [comment]
Thanks, it's working great now as of 1.2.1.  

I also noticed you made a change to bubble up the touch auth error reason - nice!  In the future you might make that sort of change with a minor revision number bump (i.e. 1.3 instead of 1.2.1) - my old code was not backward compatible.  I'm happy to see the extra tweak make it in but folks who get the change by surprise might think otherwise :) 

Thanks again... closing this issue now.

**Comment by liu044100** [comment]
@moliveira1981 Sorry for the unsuitable version naming, I'll pay attention next time. 😬
