### ISSUE TITLE
FaceID crashing on iOS 12

### ISSUE THREAD

**Issue by rvoortman** [recruit-lifestyle/Smile-Lock#63]
I've noticed FaceID crashing on iOS 12. This seems to happen on all phones with FaceID (including the iPhone X, XR en S Max). 

**Steps to Reproduce:**
1. Enable FaceID
2. Open the smile lock password screen
3. Click the FaceID button
4. Crash

The stacktrace doesn't say much to me, but perhaps this will say something to someone:
```
libsystem_kernel.dylib`__abort_with_payload:
    0x112d3a014 <+0>:  movl   $0x2000209, %eax          ; imm = 0x2000209 
    0x112d3a019 <+5>:  movq   %rcx, %r10
    0x112d3a01c <+8>:  syscall 
->  0x112d3a01e <+10>: jae    0x112d3a028               ; <+20>
    0x112d3a020 <+12>: movq   %rax, %rdi
    0x112d3a023 <+15>: jmp    0x112d1ce67               ; cerror_nocancel
    0x112d3a028 <+20>: retq   
    0x112d3a029 <+21>: nop    
    0x112d3a02a <+22>: nop    
    0x112d3a02b <+23>: nop    
```

Possible related to https://www.howtoisolve.com/face-id-not-working-on-iphone-x/.

**Comment by igorkulman** [comment]
Getting the crash reports from my users also, I think it is related to `NSFaceIDUsageDescription` missing in my `Info.plist`

**Comment by rvoortman** [comment]
> Getting the crash reports from my users also, I think it is related to `NSFaceIDUsageDescription` missing in my `Info.plist`

Thank you, this was indeed the issue. Closing this issue, since it's not directly smile-lock related, however, I still think the docs should mention this somewhere.
