### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by dernise** [recruit-lifestyle/Smile-Lock#9]
Hey, iOS 10 is available next week, would it be possible to have a swift 3 branch ?
Thank you!

**Comment by liu044100** [comment]
Hi, @dernise.

I will make swift 3 branch later, maybe three days later. 😬

**Comment by sochalewski** [comment]
What about today or tomorrow? :P

**Comment by liu044100** [comment]
@sochalewski Sorry about it, I just make a swift3 branch, but so busy to fix the swift3 sytanx...

**Comment by liu044100** [comment]
@dernise @sochalewski sorry for update pod later, now the version 2.0.0 support swift3.

**Comment by sochalewski** [comment]
@liu044100 Cool, love to see Swift 3 update. I will check it out tomorrow :)
